### PR TITLE
Fixed AWS EKS ami value

### PR DESCRIPTION
**Pull request by Tirke**
I updated the AMI value we look for. Maybe it's related to changes requested by @lukehoban in #3 .

### CODE REVIEW

**Comment by lukehoban** [comment]
Based on the description at https://aws.amazon.com/about-aws/whats-new/2018/08/new-amazon-eks-optimized-ami-and-cloudformation-template-for-worker-node-provisioning/, I suspect that a larger change is required here.  In particular - they say there:

> Please see the AWS documentation for more information on updating an existing CloudFormation stack to use the new CloudFormation template. **The new EKS-optimized AMI and Cloudformation template must be used together**. You will need to update the NodeImageID parameter to the new AMI ID when updating your stack.

/cc @pgavlin

**Comment by Tirke** [comment]
I've looked at everything in this article, the [linked repo](https://github.com/awslabs/amazon-eks-ami/blob/master/amazon-eks-nodegroup.yaml) and the only thing I can understand is that you need to specify a AMI Id when using [this CF template](https://github.com/awslabs/amazon-eks-ami/blob/master/amazon-eks-nodegroup.yaml) where previously it was inferred (so tight coupling).

We were not as coupled to the AMI ID because we are using the pulumi getAmi method ? So I thought that just updating this value would be sufficient. But yeah maybe I'm missing something. However the fix is working good, I managed to deploy one EKS cluster with a NGINX deploy + service successfully.

**Comment by pgavlin** [comment]
From the linked article (emphasis mine):

> Previously, the EKS-optimized AMI and CloudFormation template used to launch worker nodes for an EKS cluster were tightly coupled. The EKS-optimized AMI required UserData from the CloudFormation template to properly boot and check into an EKS cluster, making it difficult to use any method besides CloudFormation to provision worker nodes for an EKS cluster.
> 
> Now, there is a new EKS-optimized AMI and Cloudformation template that refactors and breaks out the EKS-optimized AMI UserData into a separate script simplifies the bootstrapping process for EKS worker nodes and removes the dependency on the Cloudformation template. *This makes it significantly easier to provision nodes for an EKS cluster using the AWS CLI or another provisioning tool, such as Terraform*.

I think that we'll be fine using this AMI. I do think that we may want to make some additional changes, though, in order to simplify the `UserData` we use in the ASG's `LaunchConfiguration`. Something along the lines of this should work, according to https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L9-L18 and https://github.com/awslabs/amazon-eks-ami/blob/master/amazon-eks-nodegroup.yaml#L310-L319:

```diff
diff --git a/nodejs/eks/cluster.ts b/nodejs/eks/cluster.ts
index 3f70bfc..795f8db 100644
--- a/nodejs/eks/cluster.ts
+++ b/nodejs/eks/cluster.ts
@@ -276,28 +276,12 @@ export class Cluster extends pulumi.ComponentResource {
             .apply(([id]) => id);

         const awsRegion = pulumi.output(aws.getRegion({}, { parent: this }));
-        const userdata = pulumi.all([awsRegion, eksCluster.name, eksCluster.endpoint, eksCluster.certificateAuthority])
-            .apply(([region, clusterName, clusterEndpoint, clusterCertificateAuthority]) => {
-                return `#!/bin/bash -xe
-
-CA_CERTIFICATE_DIRECTORY=/etc/kubernetes/pki
-CA_CERTIFICATE_FILE_PATH=$CA_CERTIFICATE_DIRECTORY/ca.crt
-mkdir -p $CA_CERTIFICATE_DIRECTORY
-echo "${clusterCertificateAuthority.data}" | base64 -d >  $CA_CERTIFICATE_FILE_PATH
-INTERNAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
-sed -i s,MASTER_ENDPOINT,${clusterEndpoint},g /var/lib/kubelet/kubeconfig
-sed -i s,CLUSTER_NAME,${clusterName},g /var/lib/kubelet/kubeconfig
-sed -i s,REGION,${region.name},g /etc/systemd/system/kubelet.service
-sed -i s,MAX_PODS,20,g /etc/systemd/system/kubelet.service
-sed -i s,MASTER_ENDPOINT,${clusterEndpoint},g /etc/systemd/system/kubelet.service
-sed -i s,INTERNAL_IP,$INTERNAL_IP,g /etc/systemd/system/kubelet.service
-DNS_CLUSTER_IP=10.100.0.10
-if [[ $INTERNAL_IP == 10.* ]] ; then DNS_CLUSTER_IP=172.20.0.10; fi
-sed -i s,DNS_CLUSTER_IP,$DNS_CLUSTER_IP,g /etc/systemd/system/kubelet.service
-sed -i s,CERTIFICATE_AUTHORITY_FILE,$CA_CERTIFICATE_FILE_PATH,g /var/lib/kubelet/kubeconfig
-sed -i s,CLIENT_CA_FILE,$CA_CERTIFICATE_FILE_PATH,g  /etc/systemd/system/kubelet.service
-systemctl daemon-reload
-systemctl restart kubelet kube-proxy
+        const clusterCaData = eksCluster.certificateAuthority.apply(ca => Buffer.from(ca.data).toString("base64"));
+        const userdata = pulumi.all([awsRegion, eksCluster.name, eksCluster.endpoint, clusterCaData])
+            .apply(([region, clusterName, clusterEndpoint, clusterCa]) => {
+                return `#!/bin/bash
+
+/etc/eks/bootstrap.sh ${clusterName} --apiserver-endpoint ${clusterEndpoint} --b64-cluster-ca ${clusterCa}
 `;
             });
         const eksWorkerAmi = aws.getAmi({
```

**Comment by lukehoban** [comment]
Merging this in as is - but will leave #3 open for now to track any further improvements we can make per @pgavlin's comment.

Thanks @Tirke!

**Pull request merged**
